### PR TITLE
Revert "pthread_cond: only call futex_wake when there are waiters"

### PR DESCRIPTION
**Pull request by ShevT**
* Fixes portrait mode libraries for OxygenOS camera.

* This reverts commit 9c08f4fecc5a8179426c4436071e6a451396eb38.

Change-Id: Ib914dc6685004fb4da487f2f7e8798869e299e10

### CODE REVIEW

**Comment by gwolf2u** [comment]
does this affect anything else?

**Comment by ShevT** [comment]
> does this affect anything else?

I did not find. Everything seems to be working fine.

**Comment by xNombre** [comment]
@ShevT isn't is hex patched here? https://review.lineageos.org/c/LineageOS/android_device_oneplus_sm8350-common/+/327343

**Comment by ShevT** [comment]
> @ShevT isn't is hex patched here? https://review.lineageos.org/c/LineageOS/android_device_oneplus_sm8350-common/+/327343

we don't have it

**Pull request merged**
